### ISSUE TITLE
TacocoRunner w/o pom.xml modification

### ISSUE THREAD

**Issue by junghuk** [spideruci/tacoco#10]
I changed TacocoRunner class to run multiple test cases.
It works with my 2 projects so far, but I think I need more tests.

**Comment by VijayKrishna** [comment]
I carried out a detailed exploratory test with SourceSurfer as pointed out in pull request #11. The notes for that test-session are available in notes.md. I am closing this issue for now.

Any future bugs/issues, while working with other systems, should be identified with new bugs/issues in the issue-tracker.
