### ISSUE TITLE
Unable to parse `end` session in jacoco.exec, as produced by commons-text

### ISSUE THREAD

**Issue by VijayKrishna** [spideruci/tacoco#14]
ExecAnalyzer is unable to encounter the `end` session in the jacoco.exec file that was produced for the commons-text project: https://github.com/junghuk/text.

Possible issues:
- Parser does not parse all the way to the end.
- the `end` session does not exist in jacoco.exec
  - this might imply a bug in TacocoListener.

For further context, refer to the diagnosis of Issue #13 as follows. (Copied from Issue #13)

Diagnosis: the ExecutionDataParser, expects the last session to have the id, end (this is related to Issue #3). When it sees that the end session has been reached, it properly terminates the printing of the JSON dump, by adding a closing bracket in the of the dump.

Now, in the case of commons-text, that is not the last session, instead this is the last recorded session id: testMissingMetric(org.apache.commons.text.similarity.StringMetricFromTest). Because it never encounters the end session, it never properly terminates the JSON dump with the closing bracket.

And so, when this "incomplete" JSON dump is read by the CoverageJsonReader, it expects more JSON elements at the end, because the JSON was never properly terminated. And so, while it is trying to read in the next non-whitespace character at the end of the JSON, it sees that it has reached the End-Of-File, and thus throws an exception, as shown in the stacktrace:

 Caused by: java.io.EOFException: End of input at line 85 column 1
at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1414)

So, the root cause seems to be with the TacocoListener itself that for some reason never records the end session. I will open another issue for that. But for now, i will submit a quick-fix for this.

**Comment by VijayKrishna** [comment]
My suspicion is that because we are now manually invoking each unit test-class in a programmatic manner, the so-called end session never gets called like it would have had a typical junit-test-runner invoked the tests instead.

**Comment by junghuk** [comment]
I tested bug fix and now it works fine.

**Comment by VijayKrishna** [comment]
the implementation no longer depends on the `end` session. JSON dump now closed properly with an empty array.
