### ISSUE TITLE
Running Test Cases in Parallel

### ISSUE THREAD

**Issue by VijayKrishna** [spideruci/tacoco#22]
Desired characteristics:
- [ ] Detect number of cores/processors + amount system memory, on the host machine to calibrate the number of parallel threads.
- [ ] Detect crashing tests and report them separately.
- [ ] Rerun crashing tests sequentially, not in parallel.
- [ ] Provide a "dry-run" mode that will show how the tests will be queued on different threads; but this mode should not actually run the tests.
- [ ] Log time it took for running each test.

List more here:

**Comment by junghuk** [comment]
I add an option, tacoco.thread, which defines number of junit runner thread.
Default value is 1.
ex)  -Dtacoco.thread=4

**Comment by VijayKrishna** [comment]
are each of the check lists in the list above completed? if not, why did we choose to not do the incomplete ones?
