### ISSUE TITLE
Include and Exclude test cases depend on configuration

### ISSUE THREAD

**Issue by junghuk** [spideruci/tacoco#25]
Read pom.xml and decide which test cases are executed.

**Comment by VijayKrishna** [comment]
Should we enable a listing of all tests for the user to have a master list to select from?

**Comment by junghuk** [comment]
In case of Joda-Time, mvn test executes 4,162 cases in 10sec without failure. 
But tacoco runner executes 12,544 cases in 184sec with 60 failures.

joda-time's pom.xml indicates that it tests only TestAllPackages.java.
If tacoco runner executes only TestAllPackages.java, it takes 50sec with 0 failure.
Output file, jacoco.exec, is much smaller.

I think this feature is necessary for batch processing to reduce time and space.

**Comment by VijayKrishna** [comment]
I see what you are saying ... got it. I imagine that you will make changes in TacocoRunner for this issue?

**Comment by junghuk** [comment]
Yes, now I'm putting this to TacocoRunner class. After making builder class, I'll move this to builder.

**Comment by junghuk** [comment]
Done.
