### ISSUE TITLE
Tacoco DataBase

### ISSUE THREAD

**Issue by junghuk** [spideruci/tacoco#31]
Parsing jacoco.exec then put it into db.

Tacoco Database Diagram(draft version)
![diagram](https://cloud.githubusercontent.com/assets/11988461/9868855/8630a44e-5b32-11e5-8939-152c5a34db7f.jpg)

**Comment by VijayKrishna** [comment]
What is FQN?

**Comment by junghuk** [comment]
Fully Qualified Name
ex) test:   org.spideruci.tacoco.AbstractBuildProbeTest.getInstanceTest
      src:   org.spideruci.tacoco.AbstractBuildProbeTest.java
      project: tacoco

**Comment by junghuk** [comment]
Create sqlite3 database output using tacoco.db option
