### ISSUE TITLE
Analyzer and Reader need name of exec file produced by Launcher

### ISSUE THREAD

**Issue by VijayKrishna** [spideruci/tacoco#34]
the analyzer and reader utilities of Tacoco should know the name of the exec file produced by the launcher

**Comment by junghuk** [comment]
use tacoco.project option to specify output file name.
ex) -Dtacoco.project=junit
output files: junit.exec
                   junit.err
                   junit.log

Also you can specify output file directory by using tacoco.outdir

**Comment by VijayKrishna** [comment]
is there a default `tacoco.outdir`?

**Comment by junghuk** [comment]
Yes, default tacoco.outdir is tacoco.home/tacoco_output.
I think I need to add more information about all tacoco options in readme.md

**Comment by VijayKrishna** [comment]
You will need to create a help menu for Launcher in the CLI's code like i did for the Analyzer and Reader commands. ... refer to this issue: #39
