### ISSUE TITLE
package org.junit.runner does not exist

### ISSUE THREAD

**Issue by maxcn** [spideruci/tacoco#4]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project tacoco: Compilation failure: Compilation failure:
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoRunner.java:[3,24] package org.junit.runner does not exist
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoRunner.java:[6,35] cannot find symbol
[ERROR] symbol: class JUnitCore
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoListener.java:[3,24] package org.junit.runner does not exist
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoListener.java:[4,24] package org.junit.runner does not exist
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoListener.java:[5,37] package org.junit.runner.notification does not exist
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoListener.java:[6,37] package org.junit.runner.notification does not exist
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoListener.java:[11,37] cannot find symbol
[ERROR] symbol: class RunListener
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoListener.java:[15,36] cannot find symbol
[ERROR] symbol:   class Description
[ERROR] location: class org.spideruci.tacoco.TacocoListener
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoListener.java:[21,37] cannot find symbol
[ERROR] symbol:   class Result
[ERROR] location: class org.spideruci.tacoco.TacocoListener
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoListener.java:[27,33] cannot find symbol
[ERROR] symbol:   class Description
[ERROR] location: class org.spideruci.tacoco.TacocoListener
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoListener.java:[34,34] cannot find symbol
[ERROR] symbol:   class Description
[ERROR] location: class org.spideruci.tacoco.TacocoListener
[ERROR] /Users/maxwei/git/tacoco/src/main/java/org/spideruci/tacoco/TacocoRunner.java:[22,17] cannot find symbol
[ERROR] symbol:   class JUnitCore
[ERROR] location: class org.spideruci.tacoco.TacocoRunner
[ERROR] -> [Help 1]

**Comment by VijayKrishna** [comment]
this was a good catch @maxcn ... turns out that you cannot just scope junit to the test phase of maven because junit's classes (Runner and Description) are being used by TacocoListener. I was the cluprit here... my fault. It is now fixed.

**Comment by maxcn** [comment]
thanks a lot
