### ISSUE TITLE
Using Jacoco Maven Plugin as a dependency

### ISSUE THREAD

**Issue by tariq1890** [spideruci/tacoco#43]
As per the Jacoco developers , It is not recommended to use the plugin as a dependency. Since the Jacoco classes are being used , we can directly reference the libraries they fall under instead of referring to the jacoco maven plugin.

For eg:- Jacoco Maven plugin also created a challenge when implementing Maven Embedder. Since Maven Embedder uses the class DefaultPlexusContainer . It took the DefaultPlexusConttainer contained in the jar " plexus-container-default-1.0-alpha-9-stable-1" which is a dependency from adding the jacoco maven plugin in the pom. To work around this problem, I had to move the dependency tag of jacoco maven plugin to the last in the list of tags in the pom.xml , so that maven embedder would work.

I propose the usage of the following artifacts instead of including Jacoco Maven plugin as a dependency

org.jacoco.report
org.jacoco.agent.rt
org.jacoco.core

These dependencies contain all the Jacoco classes being used in the tacoco project. I am  able to build and run the project with this.

Please let me know , If I can submit a pull request for this.

**Comment by VijayKrishna** [comment]
send the pull request.

**Comment by tariq1890** [comment]
@VijayKrishna I have sent the pull request!

**Comment by VijayKrishna** [comment]
@tariq1890 thank you for these pull requests ... i hope you are enjoying working on the project ... keep them coming.

**Comment by tariq1890** [comment]
You are most welcome. I am glad to help :)
