### ISSUE TITLE
JUnitRunner does not execute in Windows systems

### ISSUE THREAD

**Issue by tariq1890** [spideruci/tacoco#46]
The separator for Unix is "/", while for Windows , it is "\"

Similarly the pathSeparator is ":" for Unix , whereas for WIndows we use ";"

We can use the static variables available in the java File library which will resolve to the appropriate delimiter for the OS it is running on.

For all hard-coded occurences of these delimiters, we can place the static variables instead and make the program OS-independent. Let me know If I can deliver this in a pull request?

**Comment by VijayKrishna** [comment]
I imagine that you can use something like File.pathSeparator and File.separator, or better yet System.getProperty("seperator") and System.getProperty("path.seperator")?

**Comment by tariq1890** [comment]
I will be using File.pathSeparator and File.separator as they are static variables initialized to the the System property variables.

I have tested my changes and It is working as before. Once pull request #45 is merged, I can submit this as well!

**Comment by tariq1890** [comment]
Pull request submitted ! https://github.com/spideruci/tacoco/pull/47

**Comment by VijayKrishna** [comment]
Pull Request #47 has now been merged.
