### ISSUE TITLE
Logs are not printed during Maven operations

### ISSUE THREAD

**Issue by tariq1890** [spideruci/tacoco#48]
After moving to Maven Embedder, we are unable to see the maven build logs in the console. This can be resolved after adding slf4j as a dependency in the tacoco pom

```
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
</dependency>
```

No code changes required!

**Comment by VijayKrishna** [comment]
can you explain this fix? How come no code changes are needed?

**Comment by tariq1890** [comment]
The class MavenCli.java uses ILoggerFactory for its logging mechanism. Adding the slf4j dependency will make the slf4j classes get loaded by the classloader and the ILoggerFactory will be instatiated to those classes during runtime.

**Comment by VijayKrishna** [comment]
How important are these logs? What do they provide? And how is it that MavenCli is able to function without slf4j as its dependency?

**Comment by tariq1890** [comment]
The Logs enable us to see the maven build process (the messages we see after we run maven commands).  So its more like a nice-to-have feature.

Yes MavenCli can function properly, as SLF4jLoggerFactory is not fail-fast . I guess its because logging frameworks are more of an enhancement and they shouldn't really stop the application  , if logging classes aren't tloaded by  the classloader.

Right now, we get this warning message everytime we start TacocoLauncher

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by VijayKrishna** [comment]
But why is sfl4j not a dependency to the MavenCLI that is transitively included in the class path?

**Comment by tariq1890** [comment]
The following is an excerpt from the Maven Embedder Pom. As you can see slf4j-simple dependency has been regarded as optional. slf4j-api has the interface. slf4j-simple has the implementing class

```
<dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <optional>true</optional>
    </dependency>
```

**Comment by tariq1890** [comment]
Hey @VijayKrishna  , What would your opinion be on this?

**Comment by VijayKrishna** [comment]
My plan was incorporate this fix with the other pull request that you submitted. We are currently adding the facility to use Checkstyle to maintain some consistency in our coding standards and formats. This has caused changes across the code base (all of them are changes in the indentation.) once they are done, I plan on incorporating all your changes.

But, if you want my frank opinion, I think that such logs are an overkill and they are best avoided -- they make things go slow. However, like you said, they are surely a nice to have feature. It would be nice if we can turn off logging when we do not need it using a command line argument or something -- this is something we can look to do going forward.

**Comment by VijayKrishna** [comment]
Added a dependency for slf4j, check if it is working at your end. I will close this issue after your confirmation.

**Comment by tariq1890** [comment]
Its working :) . I can look into the log toggling. So can we keep the issue open until then?

**Comment by VijayKrishna** [comment]
Sure... can you list the steps that you took to run this on your end, along with a snapshot of the kind of logs that you are seeing?

Update: Ideally specify what you need to do on the command line to get this to work.

**Comment by tariq1890** [comment]
![log screenshot](https://cloud.githubusercontent.com/assets/2658224/11129396/0663d56e-89a5-11e5-9e2b-96ceca6136af.png)

I am just running tacoco launcher and these logs get printed on the console

**Comment by tariq1890** [comment]
I have pushed the latest commit for switching log levels. Please check commit Id dfbe2fabc98b5a6928b07deac7403fd18c9f2133
