### ISSUE TITLE
where to find the output of mvn exec:java .......

### ISSUE THREAD

**Issue by maxcn** [spideruci/tacoco#5]
HI Vijay, thanks for your help. I get your execAnalyzer running on my local mac. However, I don't know how to get the output of the command mvn exec:java ...
just like :

"template_view_should_be_rendered_with_given_model_view_object(spark.GenericIntegrationTest)": Tue May 19 00:44:54 PDT 2015 - Tue May 19 00:44:54 PDT 2015
[{"name":"InputStreamSerializer.java","packagename":"spark/webserver/serialization","format":"DENSE","firstLine":30,"lines":[1077937472]},{"name":"SerializerChain.java","packagename":"spark/webserver/serialization","format":"DENSE","firstLine":32,"lines":[1146176768,1310720]},{"name":"BytesSerializer.java","packagename":"spark/webserver/serialization","format":"DENSE","firstLine":28,"lines":[1077937493,83886080]},{"name":"DefaultSerializer.java","packagename":"spark/webserver/serial

**Comment by VijayKrishna** [comment]
Do you think that a user should be able to specify the path to a json file in the input args? like this: `mvn exec:java -Dexec.args="/project/path/of/your/system/under/test/ /path/to/your/jacoco.exec /path/to/json/output"`? Will that do the trick?

**Comment by maxcn** [comment]
I saw some posts giving instructions to specifies the output file in maven pom.xml and didn't see any command line solution. Keep searching.

**Comment by VijayKrishna** [comment]
I meant that i will have to provide the ability to let users give that as command line arguments. But if you could give that as command line arguments, will that work for you --- for this feature request?

**Comment by maxcn** [comment]
yes, I think so

**Comment by VijayKrishna** [comment]
@maxcn check it out ... and read the updated usage instructions in the README. If you are able to use it successfully based on the usage instructions, i will close this issue.

**Comment by maxcn** [comment]
cool, it works for me. Please close this issue.

**Comment by VijayKrishna** [comment]
That sounds great! I think this branch is also finally ready to be merged back into master :+1: Thanks @maxcn for trying this out!
