### ISSUE TITLE
Optimizing the PITHandler methods

### ISSUE THREAD

**Issue by tariq1890** [spideruci/tacoco#57]
Hey @junghuk @VijayKrishna ,

I was having a look at the PITHandler/runPit()method and I had a few suggestions.
1. The formal parameters classpath and targetDir aren't required in this method as these values are already contained inside the probe object. 
2. Also, line 255 causes a compilation error when you use Java 7. If you guys want to make tacoco compatible with Java 7 (this is up to you guys) we can change line 255 from 
   
   ```
   Files.readAllLines(Paths.get(pitErrFile.toURI())
   ```
   
   to
   
   ```
   Files.readAllLines(Paths.get(pitErrFile.toURI(), StandardCharsets.UTF_8)))
   ```

Looking at  the source code of Java 8 java.nio.file.Files this change will have no side impacts whatsoever.
1.  In Line 212, pitest-1.1.7 has been hardcoded, if we were to upgrade to another version, we'd have to change the code as well. Can we use the classpath string variable itself over here? It does contain the path to the pitest jar libs.

If these changes sound okay, I can submit a pull request.

**Comment by VijayKrishna** [comment]
Both @junghuk and I are in the process of refactoring the code base at the moment, and PITHandler is one of the things that we are looking to change in its fundamentals. Thanks for highlighting these issues -- they should be resolved in the upcoming days.

**Comment by junghuk** [comment]
@tariq1890 thanks for the points.
I updated PIT related code in instruments branch including your suggestions.
If you have any other concern, or missing, please leave comments.

**Comment by tariq1890** [comment]
Sure. I will check and get back

**Comment by tariq1890** [comment]
Hey @junghuk  , 

Just one question

-Will you be adding the StandardCharsets.UTF_8 parameter in Line 107 of PITHandler.java ? Only if you want Java 7 compatibility.  If Tacoco mandates Java 8, this can be ignored :)

**Comment by junghuk** [comment]
@tariq1890 Since I'm using java8, I did not catch the character set problem. Anyways, using StandardCharsets.UTF_8 seems no harm. If you summit a pull request for that, I'll accept. Thanks.

**Comment by tariq1890** [comment]
I have submitted the request #60
