### ISSUE TITLE
Can we make the option of specifying the jacoco runtime and pit analyze classpath as VM arguments optional?

### ISSUE THREAD

**Issue by tariq1890** [spideruci/tacoco#59]
Based on the new changes in the instruments branch, the jacoco runtime and pit jar paths are specified as VM arguments.
C
Could we programmatically retrieve these jar locations instead of specifying via VM arguments? Two reasons why I propose this
- Too many VM arguments can make one sad. (Or Maybe its just me! )
- Since jacoco jars are already used in the code, specifying a jacoco agent jar of a different version can cause potential issues in the form of NoSuchMethodError or ClassNotFoundException or other unexpected outcomes.

[JARPathUtil.txt](https://github.com/spideruci/tacoco/files/41113/JARPathUtil.txt)

If you guys are okay with this change, Please check the java util file I have attached above, to programmatically retrieve the jar file path and jar file name.

You can also check out my repository https://github.com/tariq1890/MavenEmbedTest where you can see the code in action.  I have tested this logic in MAC and Windows. Works fine :)

**Comment by junghuk** [comment]
@tariq1890 I'm interested in your warpath code. However, my intention in recent changes in the instrument branch is 
- a user can specify her own javaagent.
- a user can specify his own pit jar. (I do have my own pit jar, which runs all tests.)

**Comment by tariq1890** [comment]
@junghuk Sure. So I have edited the Issue title. 

Can we make these VM arguments optional? If the user does not specify the jacoco java agent or the pit jars, we can use the jars contained in our dependencies using the JARPathUtil. Does this sound okay?

**Comment by VijayKrishna** [comment]
@tariq1890 you are missing the point (in part because we have not done a good job with stating the point). These changes are trying to make it such that we can plug in any analysis, not just Jacoco. And you are specifying the analysis as VM arguments in the config files (typically as the Javaagent.)

**Comment by tariq1890** [comment]
I understand now. I assumed you guys will be using jacoco only because tacoco uses the jacoco classes.(like CounterImpl, IAgent etc.). My bad!
