### ISSUE TITLE
analyzer.opts parameter is missing in the tacoco wiki

### ISSUE THREAD

**Issue by tariq1890** [spideruci/tacoco#66]
Please add the analyzer.opts parameter to the Tacoco wiki. 

Also Please let me know what I should be providing for this argument as I need to start testing my new changes in tacoco.

**Comment by junghuk** [comment]
I updated wiki page. analyzer.opts specifies configuration file. 
example,
Danalyzer.opts="configs/tacoco-analyzer.config"
configfile: https://github.com/spideruci/tacoco/blob/master/configs/tacoco-analyzer.config

**Comment by tariq1890** [comment]
Thanks!
