### ISSUE TITLE
tacoco fails with Null pointer Exception if no test-class found in the test class folder

### ISSUE THREAD

**Issue by reetasingh** [spideruci/tacoco#80]

**Comment by reetasingh** [comment]
If tacoco does not find any test class inside the folder. It fails with Null pointer Exception. 

In the method runTests in AbstractRuntimeAnalyzer, the AbstractTestRunner  sets to null if AbstractBuildProbe does not return any testclass. This leads to Null pointer exception when runner tries to run the class.

protected void runTests(List<Class<?>> klasses) {
		List<Future<AnalysisResults>> futureAnalysisResults = new ArrayList<>();
		int nThread  = Integer.parseInt(readOptionalArgumentValue(THREAD, "1"));
		ExecutorService threadPool = Executors.newFixedThreadPool(nThread);
		AbstractTestRunner runner = AbstractTestRunner.getInstance(this.buildProbe); // Here runner is null if no test class found.

**Comment by reetasingh** [comment]
Hanlding the null case with simple if-else check. If null - then print No test class found and exit. Else move ahead.

**Comment by VijayKrishna** [comment]
who is heading up the merge for this?
